if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

if [ -f ~/.bash_script ]; then
    . ~/.bash_script
fi
source /users/zhangkai/Projects/git-bash-completion/git-completion.bash

export PATH=/usr/local/bin:$PATH
