alias ..='cd ..'
alias ...='cd ../../'
alias _='cd -'
alias ls='ls -hF -G'  # add colors for filetype recognition
alias ll='ls -l -h'
alias la='ls -A'
alias du='du -kh' 
alias df='df -kTh'
alias head='head -n 20'

# Colored output in grep
alias grep='grep --color=auto'

# Making solarized work with tmux
alias tmux="TERM=screen-256color-bce tmux"

# some git aliases
alias gitp='git pull --rebase'
alias gitst='git status'
alias gitcl='git clone'
alias git1diff='git diff HEAD~1 HEAD'
alias gitdfile='git diff --name-only'
alias gitcmt='git commit'
alias gitpo='git push origin'
alias gitab='git branch -a'
alias gitsth='git stash'
alias gitsthap='git stash apply'
alias gitprune='git remote prune origin'

#pygmentize
alias catfmt='pygmentize -O style=monokai -f console256 -g'

# proxychains
alias proxychains='proxychains4'

#hash
alias sha1='openssl sha1'
alias md5='md5 -r'

#clipboard
alias pbc='pbcopy'
alias pbp='pbpaste'

#homebrew
alias brewp='proxychains brew'
